In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
df.info()
df.describe(include="all")
df["Churn"].value_counts()
df.groupby("Contract")["Churn"].value_counts(normalize=True)

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

Contract        Churn
Month-to-month  No       0.572903
                Yes      0.427097
One year        No       0.887305
                Yes      0.112695
Two year        No       0.971681
                Yes      0.028319
Name: proportion, dtype: float64

In [1]:
df.shape
df.columns.tolist()
df.info()
df.isnull().sum()
df.duplicated().sum()

NameError: name 'df' is not defined

In [2]:
import pandas as pd

In [3]:
df.shape
df.columns.tolist()
df.info()
df.isnull().sum()
df.duplicated().sum()

NameError: name 'df' is not defined

In [4]:
import pandas as pd

df = pd.read_csv("../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.shape
df.columns.tolist()
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

np.int64(0)

In [6]:
df.shape

(7043, 21)

In [7]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [9]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df["TotalCharges"].head(10)

0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
5      820.5
6     1949.4
7      301.9
8    3046.05
9    3487.95
Name: TotalCharges, dtype: str

In [12]:
df.shape
df.columns.tolist()
df.info()
df.isnull().sum()
df.duplicated().sum()
df["TotalCharges"].head(10)

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
5      820.5
6     1949.4
7      301.9
8    3046.05
9    3487.95
Name: TotalCharges, dtype: str

In [13]:
(df["TotalCharges"] == " ").sum()

np.int64(11)

In [14]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [15]:
df["TotalCharges"].isnull().sum()

np.int64(11)

In [16]:
df = df.dropna(subset=["TotalCharges"]).copy()

In [17]:
df["TotalCharges"].isnull().sum()

np.int64(0)

In [18]:
df.shape

(7032, 21)

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

C:\Users\vijyadla\AppData\Local\Temp\ipykernel_32104\1126013313.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [21]:
for col in df.select_dtypes(include=["object", "string"]).columns:
    df[col] = df[col].str.strip()

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.2 MB

In [23]:
df.to_csv("../data/processed/churn_cleaned.csv", index=False)
print("Saved cleaned file")

Saved cleaned file

In [24]:
(df["TotalCharges"] == " ").sum()
df["TotalCharges"].isnull().sum()
df.shape
df.duplicated().sum()
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.2 MB

In [25]:
quality_report = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "missing_values": df.isnull().sum().values,
    "non_null_count": df.notnull().sum().values,
    "unique_values": [df[col].nunique() for col in df.columns]
})

quality_report

              column    dtype  missing_values  non_null_count  unique_values
0         customerID      str               0            7032           7032
1             gender      str               0            7032              2
2      SeniorCitizen    int64               0            7032              2
3            Partner      str               0            7032              2
4         Dependents      str               0            7032              2
5             tenure    int64               0            7032             72
6       PhoneService      str               0            7032              2
7      MultipleLines      str               0            7032              3
8    InternetService      str               0            7032              3
9     OnlineSecurity      str               0            7032              3
10      OnlineBackup      str               0            7032              3
11  DeviceProtection      str               0            7032              3
12       TechSupport      str               0            7032              3
13       StreamingTV      str               0            7032              3
14   StreamingMovies      str               0            7032              3
15          Contract      str               0            7032              3
16  PaperlessBilling      str               0            7032              2
17     PaymentMethod      str               0            7032              4
18    MonthlyCharges  float64               0            7032           1584
19      TotalCharges  float64               0            7032           6530
20             Churn      str               0            7032              2

In [26]:
rows_before = 7043
rows_after = len(df)
rows_removed = rows_before - rows_after
duplicate_rows = df.duplicated().sum()

summary_stats = pd.DataFrame({
    "metric": [
        "rows_before_cleaning",
        "rows_after_cleaning",
        "rows_removed",
        "duplicate_rows_after_cleaning"
    ],
    "value": [
        rows_before,
        rows_after,
        rows_removed,
        duplicate_rows
    ]
})

summary_stats

                          metric  value
0           rows_before_cleaning   7043
1            rows_after_cleaning   7032
2                   rows_removed     11
3  duplicate_rows_after_cleaning      0

In [29]:
quality_report.to_csv("../data/quality/data_quality_report.csv", index=False)
summary_stats.to_csv("../data/quality/data_quality_summary.csv", index=False)

print("Saved quality report files")

Saved quality report files

In [28]:
import os
os.makedirs("../data/quality", exist_ok=True)

In [30]:
import os

os.makedirs("../data/quality", exist_ok=True)

quality_report.to_csv("../data/quality/data_quality_report.csv", index=False)
summary_stats.to_csv("../data/quality/data_quality_summary.csv", index=False)

print("Saved quality report files")

Saved quality report files

In [31]:
summary_stats

                          metric  value
0           rows_before_cleaning   7043
1            rows_after_cleaning   7032
2                   rows_removed     11
3  duplicate_rows_after_cleaning      0

In [32]:
customers = df[
    [
        "customerID",
        "gender",
        "SeniorCitizen",
        "Partner",
        "Dependents",
        "tenure"
    ]
].copy()

customers.head()

   customerID  gender  SeniorCitizen Partner Dependents  tenure
0  7590-VHVEG  Female              0     Yes         No       1
1  5575-GNVDE    Male              0      No         No      34
2  3668-QPYBK    Male              0      No         No       2
3  7795-CFOCW    Male              0      No         No      45
4  9237-HQITU  Female              0      No         No       2

In [33]:
services = df[
    [
        "customerID",
        "PhoneService",
        "MultipleLines",
        "InternetService",
        "OnlineSecurity",
        "OnlineBackup",
        "DeviceProtection",
        "TechSupport",
        "StreamingTV",
        "StreamingMovies"
    ]
].copy()

services.head()

,customerID,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Yes,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Yes,No,Fiber optic,No,No,No,No,No,No

In [34]:
billing = df[
    [
        "customerID",
        "Contract",
        "PaperlessBilling",
        "PaymentMethod",
        "MonthlyCharges",
        "TotalCharges"
    ]
].copy()

billing.head()

,customerID,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,7590-VHVEG,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,One year,No,Mailed check,56.95,1889.50
2,3668-QPYBK,Month-to-month,Yes,Mailed check,53.85,108.15
3,7795-CFOCW,One year,No,Bank transfer (automatic),42.30,1840.75
4,9237-HQITU,Month-to-month,Yes,Electronic check,70.70,151.65

In [35]:
status = df[
    [
        "customerID",
        "Churn"
    ]
].copy()

status.head()

   customerID Churn
0  7590-VHVEG    No
1  5575-GNVDE    No
2  3668-QPYBK   Yes
3  7795-CFOCW    No
4  9237-HQITU   Yes

In [36]:
print("customers shape:", customers.shape)
print("services shape:", services.shape)
print("billing shape:", billing.shape)
print("status shape:", status.shape)

customers shape: (7032, 6)
services shape: (7032, 10)
billing shape: (7032, 6)
status shape: (7032, 2)

In [37]:
import os
os.makedirs("../data/processed/tables", exist_ok=True)

In [38]:
customers.to_csv("../data/processed/tables/customers.csv", index=False)
services.to_csv("../data/processed/tables/services.csv", index=False)
billing.to_csv("../data/processed/tables/billing.csv", index=False)
status.to_csv("../data/processed/tables/status.csv", index=False)

print("Saved all split tables")

Saved all split tables

In [39]:
import os

print(os.path.exists("../data/processed/tables/customers.csv"))
print(os.path.exists("../data/processed/tables/services.csv"))
print(os.path.exists("../data/processed/tables/billing.csv"))
print(os.path.exists("../data/processed/tables/status.csv"))

True
True
True
True

In [40]:
import sqlite3

conn = sqlite3.connect("../data/processed/churn_analytics.db")

customers.to_sql("customers", conn, if_exists="replace", index=False)
services.to_sql("services", conn, if_exists="replace", index=False)
billing.to_sql("billing", conn, if_exists="replace", index=False)
status.to_sql("status", conn, if_exists="replace", index=False)

print("Loaded all tables into SQLite")

Loaded all tables into SQLite

In [41]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

import pandas as pd
pd.read_sql(query, conn)

        name
0  customers
1   services
2    billing
3     status

In [42]:
test_query = """
SELECT c.customerID, c.gender, c.tenure, b.Contract, b.MonthlyCharges, s.Churn
FROM customers c
JOIN billing b ON c.customerID = b.customerID
JOIN status s ON c.customerID = s.customerID
LIMIT 5;
"""

pd.read_sql(test_query, conn)

   customerID  gender  tenure        Contract  MonthlyCharges Churn
0  7590-VHVEG  Female       1  Month-to-month           29.85    No
1  5575-GNVDE    Male      34        One year           56.95    No
2  3668-QPYBK    Male       2  Month-to-month           53.85   Yes
3  7795-CFOCW    Male      45        One year           42.30    No
4  9237-HQITU  Female       2  Month-to-month           70.70   Yes

In [43]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../data/processed/churn_analytics.db")
print("Connected")

Connected

In [44]:
query = """
SELECT
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        100.0 * SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS churn_rate_pct
FROM status;
"""

pd.read_sql(query, conn)

   total_customers  churned_customers  churn_rate_pct
0             7032               1869           26.58

In [45]:
query = """
SELECT
    b.Contract,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN s.Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        100.0 * SUM(CASE WHEN s.Churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS churn_rate_pct
FROM billing b
JOIN status s
    ON b.customerID = s.customerID
GROUP BY b.Contract
ORDER BY churn_rate_pct DESC;
"""

pd.read_sql(query, conn)

         Contract  total_customers  churned_customers  churn_rate_pct
0  Month-to-month             3875               1655           42.71
1        One year             1472                166           11.28
2        Two year             1685                 48            2.85

In [46]:
query = """
SELECT
    b.PaymentMethod,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN s.Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        100.0 * SUM(CASE WHEN s.Churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS churn_rate_pct
FROM billing b
JOIN status s
    ON b.customerID = s.customerID
GROUP BY b.PaymentMethod
ORDER BY churn_rate_pct DESC;
"""

pd.read_sql(query, conn)

,PaymentMethod,total_customers,churned_customers,churn_rate_pct
0,Electronic check,2365,1071,45.29
1,Mailed check,1604,308,19.20
2,Bank transfer (automatic),1542,258,16.73
3,Credit card (automatic),1521,232,15.25